package com.smartisanos.launcher.model;

public enum PackageState {
    PRESENT, REPLACING, TEMPORARILY_UNAVAILABLE, DISABLED, PROFILE_UNAVAILABLE,
    PROFILE_LOCKED, PROFILE_QUIET, REMOVED_CONFIRMED, UNKNOWN
}
